### ISSUE TITLE
Question: Sample Projects?

### ISSUE THREAD

**Issue by dgerding** [mdesalvo/RDFSharp#114]
Hi,
I'm excited to see if RDFSharp is, or is a better, alternative to BrightstarDB or dotnetRDF? Are there any example projects available? Thoughts about comparisons?

Thanks

**Comment by mdesalvo** [comment]
Hi David,
thanks for your interest for the project!
[Here](https://github.com/Philippe-Laval/RDFSharpExample) is an example project from the GitHub community and also the latest library docs ([RDF](https://github.com/mdesalvo/RDFSharp/releases/download/v2.14.0/RDFSharp-2.14.0.pdf), [OWL](https://github.com/mdesalvo/RDFSharp/releases/download/v2.14.0/RDFSharp.Semantics-2.14.0.pdf)).

I would not directly compare RDFSharp to BrightstarDB, since it is just an RDF store engine coupled to dotnetRDF. So for an effective comparison I would take in consideration RDFSharp and dotnetRDF under the following spectrum of capabilities:

- RDF modeling (compliance to RDF, learnability, ease of use, data exchange capabilities, data storage capabilities, performances)
- SPARQL modeling (compliance to SPARQL, learnability, ease of use, performances)
- SHACL modeling (compliance to SHACL, learnability, ease of use, performances)
- OWL modeling (compliance to OWL, expressivity, learnability, ease of use, features)

I personally believe that, compared to dotnetRDF, RDFSharp represents the safe choice for ontology modeling (OWL, SKOS) and a quick-win choice for contexts requiring out-of-the-box graph modeling capabilities. DotnetRDF is devoted to power C#/SPARQL users, with noticeable strengths in its SPARQL parser, JSON-LD support and overall extensibility.
