### ISSUE TITLE
InverseOf relations does not accept properties detected as property chains

### ISSUE THREAD

**Issue by constnick** [mdesalvo/RDFSharp#165]
Current reasoning rule "InverseOf" is
_((F1 P1 F2) AND (P1 INVERSEOF P2)) => (F2 P2 F1)_

But why doesn't apply rule:
_(P1 INVERSEOF P2)) => (P2 INVERSEOF P1)_
?

I think, it would be correct to infer such axioms prior other.
Now, for example, inversed property for property chain not inferred (with full set of 18 base rules) - may be due to lack of that.
(Even if assert property chain manually before reasoning - pls see attachment).
Other cases also possible, i suppose.

[TEST.zip](https://github.com/mdesalvo/RDFSharp/files/5963533/TEST.zip)

**Comment by mdesalvo** [comment]
Hi,
thanks for the detailed report!

Your modeling is correct, altough I wouldn't expect the explicit assertion of a propertychain materialization (_st:Item_1 st:propChain_1-3 st:Item_3_) since this triple would be emitted anyway by the reasoner, if proper rule is given. This is however not an error.

The missing _inverseOf_ statement you complain is due to implicit validation checks aimed at preserving OWL2-DL decidability by discarding relations involving properties detected as propertychains: subPropertyOf, equivalentProperty, propertyDisjointWith and inverseOf are not accepted when one of the parts is a propertychain (a semantics warning event is generated in the background to inform of this decision). For this reason the triple _propInv_1-3 inverseOf propChain_1-3_ is not added to the property model, determining the reported behavior.

In the specific case of _inverseOf_ I understand it would be useful to accept propertychains as involved parts: I will investigate literature on how this can be done in a safe way that does not compromise OWL2-DL decidability, since the emission of the triple would feed data-related inference rules, with further emission of triples. If this is feasible, I will relax the _ RDFOntologyPropertyModel AddInverseOfRelation_ method to permit that one or both of the input properties are propertychains.

Regards,
Marco

**Comment by constnick** [comment]
Thanks, Marco,
explicit assertion of a property chain was only a test, of course. Maybe it was doubtful.
The point is implementing rule (P1 INVERSEOF P2)) => (P2 INVERSEOF P1) for any properties (even if it will not be possible for chains). 
For example, properties _prop_1-2_ and _propInv_1-2_ in test files.

**Comment by mdesalvo** [comment]
I see the inverse properties in this snippet of code, which I presume is what you're doing (or am I missing any steps?):
```
RDFSemanticsEvents.OnSemanticsInfo += ((msg) => Console.WriteLine(msg));
RDFSemanticsEvents.OnSemanticsWarning += ((msg) => Console.WriteLine(msg));
RDFNamespaceRegister.AddNamespace(new RDFNamespace("st", "http://frede.gat/stuff#"));

//Read test ontology file into a graph
RDFGraph graph = RDFGraph.FromFile(RDFModelEnums.RDFFormats.Turtle, Environment.CurrentDirectory+ "\\Stuff.TEST.RDFSharp.CopySource.ttl");

//Parse the ontology corresponding to the graph (here you should have 2 inverseOf relations in the property model)
RDFOntology ontology = RDFOntology.FromRDFGraph(graph);

//Prepare a resoner with desired rules and apply it to the ontology
RDFOntologyReasoner reasoner = new RDFOntologyReasoner();
reasoner.AddRule(RDFOntologyReasonerRuleset.ClassTypeEntailment)
        .AddRule(RDFOntologyReasonerRuleset.DifferentFromEntailment)
        .AddRule(RDFOntologyReasonerRuleset.DisjointWithEntailment)
        .AddRule(RDFOntologyReasonerRuleset.DomainEntailment)
        .AddRule(RDFOntologyReasonerRuleset.EquivalentClassTransitivity)
        .AddRule(RDFOntologyReasonerRuleset.EquivalentPropertyTransitivity)
        .AddRule(RDFOntologyReasonerRuleset.HasKeyEntailment)
        .AddRule(RDFOntologyReasonerRuleset.InverseOfEntailment)
        .AddRule(RDFOntologyReasonerRuleset.PropertyChainEntailment)
        .AddRule(RDFOntologyReasonerRuleset.PropertyEntailment)
        .AddRule(RDFOntologyReasonerRuleset.RangeEntailment)
        .AddRule(RDFOntologyReasonerRuleset.ReflexivePropertyEntailment)
        .AddRule(RDFOntologyReasonerRuleset.SameAsEntailment)
        .AddRule(RDFOntologyReasonerRuleset.SameAsTransitivity)
        .AddRule(RDFOntologyReasonerRuleset.SubClassTransitivity)
        .AddRule(RDFOntologyReasonerRuleset.SubPropertyTransitivity)
        .AddRule(RDFOntologyReasonerRuleset.SymmetricPropertyEntailment)
        .AddRule(RDFOntologyReasonerRuleset.TransitivePropertyEntailment);
RDFOntologyReasonerReport reasonerReport = reasoner.ApplyToOntology(ref ontology);

//Write down the ontology to a file (include both model and data inferences)
ontology.ToRDFGraph(RDFSemanticsEnums.RDFOntologyInferenceExportBehavior.ModelAndData)
        .ToFile(RDFModelEnums.RDFFormats.Turtle, Environment.CurrentDirectory + "\\Stuff.TEST.RDFSharp.CopySourceOUT.ttl");
```

Simmetry of owl:inverseOf is automatic: just add an inverseOf relation to the property model between object properties A and B and it will try to add _A inverseOf B_ and the corresponding inference _B inverseOf A_.

The inference rule _InverseOfEntailment_ acts only on the ontology Data, exploiting the existing set of inverseOf relations: it does not entail any model knowledge.

Let me know if this clarifies your doubts, I'll anyway check for the point on the reaxing of AddInverseOfRelation.

**Comment by constnick** [comment]
I'm not very familiar with this field yet, so I might be wrong.
Symmetry of _owl:inverseOf_ is automatic for any OWL-engine, is it right? 
But what if we make any query to triplestore, addressing to property _P2_, and there is only _P1_ asserted, triple _P1 inverseOf P2_ exists, and no explicite triple _P2 inverseOf P1_ ?
We'll receive unexpected result?

**Comment by constnick** [comment]
All right with your code, thank you!
"InverseOf" for second property inferred. 
I must have missed something, not you :)

**Comment by mdesalvo** [comment]
> I'm not very familiar with this field yet, so I might be wrong.
> Symmetry of _owl:inverseOf_ is automatic for any OWL-engine, is it right?
> But what if we make any query to triplestore, addressing to property _P2_, and there is only _P1_ asserted, triple _P1 inverseOf P2_ exists, and no explicite triple _P2 inverseOf P1_ ?
> We'll receive unexpected result?

Symmetry in general is an inference: it depends at which level the OWL engines decide to materialize it. RDFSharp makes it automatic at T-BOX level (equivalentClass, disjointWith, equivalentProperty, propertyDisjointWith, inverseOf, sameAs, differentFrom) so that you don't bother, and demands to reasoner the A-BOX aspects (emission of data composed of switched assertions using simmetric properties).

When you perform a query on a triplestore it still depends on the specific OWL engine how and when it handles reasoning: it may decide to materialize the inferences during the query, or it may rely on a preliminary materialization phase.

Regards,
Marco

**Comment by mdesalvo** [comment]
Relaxing of inverseOf relations involving property chains would require a complex calculation of strict order sets for eligibility checking. Altough we may purely rely on the "good modeling" by the ontology owner and simply trust this kind of relation, it is generally unfeasible to let property chains participate in T-BOX relations since this easily leads to decidability troubles and subsumption inconsistencies.

**Comment by constnick** [comment]
Have you decide to avoid inversions of properties defined as chains at all?
May be it can cause problems in some cases, but i think it safe enough in most and very useful.
For example, if property "is_uncle_of" defined as chain, we just can define property "is_nephew_of" as its inversion instead of creating inverse chain, and there will not be problems.
Besides well-known reasoners allow this.
