### ISSUE TITLE
URI and slashes

### ISSUE THREAD

**Issue by constnick** [mdesalvo/RDFSharp#182]
Hi Marco,
here is code:
```c#
var ontology = new RDFOntology(new RDFResource("http://test"));
var ontoClass = new RDFOntologyClass(new RDFResource("http://test#Class1"));
ontology.Model.ClassModel.AddClass(ontoClass);
```
I explicitly want class "http://test#Class1" but receive "http://test/#Class1" with slash.
For example URI for `owl:Class` is `http://www.w3.org/2002/07/owl#Class`, and this is seems to be a common naming way, without slash before `#`

**Comment by mdesalvo** [comment]
It is a path sanitization automatically applied by the .NET Uri class, try this example:
```
Uri.TryCreate("http://test#Class1", UriKind.Absolute, out Uri class1);
Uri.TryCreate("http://www.w3.org/2002/07/owl#Class", UriKind.Absolute, out Uri owlClass);
```
See that in the first case it assigns a default "/" local path on which the "#Class1" fragment is appended; in the second case you already have a "/2002/07/owl" local path on which the "#Class" fragment is appended.

I believe the first case does not represent a well-formed Uri because it does not respect the Uri standard since it misses the PATH component: {PROTOCOL}{DOMAIN}{PATH}{FRAGMENT}{QUERYSTRING}
