### ISSUE TITLE
Adding and subtracting data

### ISSUE THREAD

**Issue by constnick** [mdesalvo/RDFSharp#219]
Hi Marco,
I'll describe the case.
There is an ontology, it can be quite large.
I need to do the following (let's call it "what-if" operation) many times: add some quite small data (`RDFOntologyData`) to ontology data; make some "researches" within it with this addition; revert to original ontology; repeat with another small data; and so on.
Currently it possible only with full copying of ontology data (in it's `UnionWith` method) every time. 
Maybe it would be useful to have a methods like "AddData" and "SubtractData" that would work without fully copying. It may be more efficient in terms of performance.
Is it possible?
(I'd create my own function for this, but it needs to use some internal methods in `RDFOntologyTaxonomy`)

**Comment by mdesalvo** [comment]
Hi,
with a bit of reflection, like the example below, you should succeed at invoking the internal methods you need for completing your function (_I discourage this because it can lead to OWL integrity troubles, but I'm aware it can be a time saver for you_):
```c#
//Looks in the given object for an unaccessible method with the given name and, if found, invokes it with the given params
public static object CallUnaccessibleMethod(this object myObject, string methodName, params object[] methodParams)
{
    MethodInfo unaccessibleMethod = myObject.GetType().GetMethod(methodName, System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance);
    if (unaccessibleMethod != null) {
        return unaccessibleMethod.Invoke(myObject, methodParams);
    }
    return null;
}

//Then simply use it to invoke unaccessible methods
bool addEntryResult = (bool)myOntologyData.Relations.Assertions.CallUnaccessibleMethod("AddEntry", newTaxonomyEntry);
```

The suggested operations ("AddData" and "SubtractData") cannot be realized since only you as developer/data-scientist are precisely aware of the data which is being changed in your what-if job (which and how many added facts/literals, which and how many added relations/annotations): the library has to be agnostic in every situation, so it would have to compute anyway facts/literals/relations/annotations set operations. 
I suggest you to design your what-if job in a set of mirror classes leveraging the higher level CRUD library capabilities:

- AdderClass: adds factA, factB, factC and their relations to my data for beginning the simulation
- RemoverClass: removes factA, factB, factC and their relations from my data for retracting the simulation

Regards,
Marco

**Comment by constnick** [comment]
Ok, thanks! It looks like adding-removing one-by-one is acceptable approach.
