### ISSUE TITLE
Integrate unit testing project in solution

### ISSUE THREAD

**Issue by mdesalvo** [mdesalvo/RDFSharp#241]

**Comment by andy-soft** [comment]
Just found this apparently-fantastic Library, was eagerly using dotNetRDF previously (abandoned).

Have read all the Semantics.pdf but did not find documentation nor examples of usage of a simple query to a SPARQL endpoint 
I want to link WikiData to my project of Artificial Intelligence on ADIPTA, something is seen on:  api.adipta.co

¿Any clue where to start?
I would need some sample codes, the testing class is too succinct for me, does not connect several steps together like open connection, senr a command and,read the response, and serialize JSON or XML (found some smell of this but I did not understood it fully) 

Please can you document a little better, like a "HELLO WORLD" for DRF, 
And then give useful links to testing spaces to find resources, like DRF files, OWL namespaces, and data, 
Need some Examples of how to use any of the built-in Reasoners, for example using a FOAF RFD dataset.
Also I want to make a benchmark because I used JENA and dotNetRDF is very slow and fails a lot, therefore I dont use it any more.
Thanks in advance!
Andres

**Comment by mdesalvo** [comment]
Hi Andy,
I opened #255 task for this, it will find its way on a subproject during 2022.

In the meanwhile let me know if you have specific issues which I may help you solve with direct code examples. 
Mind that modeling (RDF) and querying (SPARQL) capabilities are covered by [this guide](https://github.com/mdesalvo/RDFSharp/releases/download/v2.26.0/RDFSharp-2.26.0.pdf) and semantic (OWL, SWRL) capabilities are covered with [this one](https://github.com/mdesalvo/RDFSharp/releases/download/v2.26.0/RDFSharp.Semantics-2.26.0.pdf).

**Comment by andy-soft** [comment]
Thanks for the PDF for RDF/SPARQL guide
I did not find it, maybe you should reference/place it on GitHub as
documentation
