### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ErichSuter** [mdesalvo/RDFSharp#245]
Hi,

We've been trying out RDFSharp for the last couple of months, and so far we have a good impression of it. But we came across the following unexpected behaviour:

We use .Net GUIDs as identities for classes, object properties and facts. But when exporting our ontology to file (after having made a graph), RDFSharp goes into an exception in some cases while trying to export an object property (classes and facts are OK). We did some testing, and believe that it happens when the object property Id starts with a number (when starting with a letter, it works OK).
Code example:
RDFOntologyObjectProperty prop_NotOK = RDFOntologyObjectProperty(new RDFResource("http://ont/properties/1"));
RDFOntologyObjectProperty prop_OK = RDFOntologyObjectProperty(new RDFResource("http://ont/properties/A"));
ont.Model.PropertyModel.AddProperty(prop);
...
RDFGraph graph = ont.ToRDFGraph(RDFSemanticsEnums.RDFOntologyInferenceExportBehavior.ModelAndData);
graph.ToFile(RDFModelEnums.RDFFormats.RdfXml, fileName);

When using "prop_NotOK", an exception is caught in RDFXml.cs, line 370: "RDFSharp.Model.RDFModelException: 'Cannot serialize RDF/Xml because: found 'autoNS1:1' predicate which cannot be abbreviated to a valid QName'".
When using "prop_OK", this does not happen.

**Library Version
RDFSharp-2.26.0

Cheers,

Erich Suter, NORCE (www.norceresearch.no)

**Comment by mdesalvo** [comment]
Dear Eric,
RDF/XML specification uses [xsd:qname](https://en.wikipedia.org/wiki/QName) datatype for the representation of predicate nodes. This datatype puts restrictions on the allowed starting character of the name part of "_prefix:name_" (e.g: it cannot start with a number). This is exactly your issue: you have predicate nodes whose shortened representation leads to an invalid xsd:qname (e.g: **http://ont/properties/1** => **autoNS:1**) so the library must signal this as an error, being uncompliant RDF/XML. You don't encounter this issue in subject or object nodes because RDF/XML uses alternative constructs to model them (rdf:about, rdf:resource), allowing usage of plain Uris.

You have 2 ways for succeeding in your case:

- Adapt Uri of resources acting as predicate nodes in your model so that can be converted to valid xsd:qname (e.g: **http://ont/properties/p1**)
- Switch to another RDF serialization (I suggest Turtle for its readability, but the library supports also N-Triples and TriX)

Regards,
Marco

**Comment by ErichSuter** [comment]
Thanks a lot for your swift answer, Marco!
I'm glad to see that the unexpected behaviour is due to wrong input from our side, and thanks for the tips on how to address the issue. &#128522;


Cheers,

Erich


[cid:norce_426cc920-64ab-4893-95d0-c29d5dab670c.png]

NORCE Norwegian Research Centre AS
norceresearch.no<https://www.norceresearch.no/>
