### ISSUE TITLE
Is there a documentation on how to use the library ?

### ISSUE THREAD

**Issue by assurancetourix** [mdesalvo/RDFSharp#79]
Hello Marco,

Thanks for the library, it seems to exactly fit our needs.
However I am not sure how I can use it.
I have built an ontology on Protégé and saved it as XML/RDF. Apparently I have to convert the file to trix, should I ? Actually when converted to trix, seems to load without problems.
How could I run SPARQL queries on the ontologies, starting from that point:

`RDFMemoryStore store = RDFSharp.Store.RDFMemoryStore.FromFile(RDFStoreEnums.RDFFormats.TriX, Application.dataPath + "/tepeeexamples.trix");`

Maybe you can give me hints, or there exists a doc I didn't find ?

Thanks!

**Comment by mdesalvo** [comment]
Hi,
here it is the latest [reference guide ](https://github.com/mdesalvo/RDFSharp/releases/download/v2.9.0/RDFSharp-2.9.0.pdf) for RDF/SPARQL modeling. 

Since you are dealing with ontologies you may probably better fit with the semantics extension of the library, which is currently available in [Nuget](https://www.nuget.org/packages/RDFSharp.Semantics/). Note that this will be fully code integrated into the main library in the next release. It gives you an ontology point of view of your data (an higher level abstraction comprising classes, restrictions, properties, facts, annotations, assertions, validation rules, inference rules) rather than plain RDF triples.

If you prefer dealing with RDF/SPARQL you can build SPARQL queries with the programmatic API and apply them on your graphs or stores to get results.

Thanks,
Marco

**Comment by mdesalvo** [comment]
[Here](https://github.com/mdesalvo/RDFSharp/files/4350687/RDFSharp.Semantics.pdf) the reference guide for working with ontologies

**Comment by assurancetourix** [comment]
Thanks very much Marco. The doc is just fine !
Wouldn't you think about putting the reference guide link to the readme page ? It deserves it :-)

**Comment by assurancetourix** [comment]
> [Here](https://github.com/mdesalvo/RDFSharp/files/4350687/RDFSharp.Semantics.pdf) the reference guide for working with ontologies



> Hi,
> here it is the latest [reference guide ](https://github.com/mdesalvo/RDFSharp/releases/download/v2.9.0/RDFSharp-2.9.0.pdf) for RDF/SPARQL modeling.
> 
> Since you are dealing with ontologies you may probably better fit with the semantics extension of the library, which is currently available in [Nuget](https://www.nuget.org/packages/RDFSharp.Semantics/). Note that this will be fully code integrated into the main library in the next release. It gives you an ontology point of view of your data (an higher level abstraction comprising classes, restrictions, properties, facts, annotations, assertions, validation rules, inference rules) rather than plain RDF triples.
> 
> If you prefer dealing with RDF/SPARQL you can build SPARQL queries with the programmatic API and apply them on your graphs or stores to get results.
> 
> Thanks,
> Marco

Thanks very much Marco. The doc is just fine !
Wouldn't you think about putting the reference guide link to the readme page ? It deserves it :-)
